---
apiVersion: v1
kind: Service
metadata:
  name: spring
  labels:
    app: spring
    service: spring
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: spring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pring
  labels:
    account: spring
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  strategy: {}
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - image: localhost:5000/spring:1.0
        name: spring
